// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJnuHvfVFep25Wez4SYgLHlP5arCfdkDc',
    appId: '1:1069433089584:android:10fbca15de8b67d81cc7f5',
    messagingSenderId: '1069433089584',
    projectId: 'origin-fda72',
    storageBucket: 'origin-fda72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWSh231Vd02R2C_L-u5fU1GtCzFu9nn4',
    appId: '1:1069433089584:ios:c427668f491055df1cc7f5',
    messagingSenderId: '1069433089584',
    projectId: 'origin-fda72',
    storageBucket: 'origin-fda72.firebasestorage.app',
    iosBundleId: 'com.example.origin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoWSh231Vd02R2C_L-u5fU1GtCzFu9nn4',
    appId: '1:1069433089584:ios:c427668f491055df1cc7f5',
    messagingSenderId: '1069433089584',
    projectId: 'origin-fda72',
    storageBucket: 'origin-fda72.firebasestorage.app',
    iosBundleId: 'com.example.origin',
  );
}
