// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.android,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHbXWiiELtRCJWwe45NLH-Yd5gFO2vdQM',
    appId: '1:418533091186:android:581b3f93cad65350c6dfeb',
    messagingSenderId: '418533091186',
    projectId: 'push123-95949',
    storageBucket: 'push123-95949.firebasestorage.app',
  );
}
